import { ThemeConfig, ThemeId } from './types';

const minimalist: ThemeConfig = {
  id: 'minimalist',
  name: 'Minimalist',
  pageBg: 'bg-gray-50',
  headerBg: 'bg-white border-b border-gray-200',
  headerTitle: 'text-gray-900 font-bold text-lg tracking-tight',
  headerSubtitle: 'text-gray-400 text-xs',
  sidebarBg: 'bg-white',
  sidebarBorder: 'border-r border-gray-200',
  formLabel: 'text-sm font-semibold text-gray-700',
  formDescription: 'text-xs text-gray-400 mt-0.5 mb-2',
  formInput:
    'w-full border border-gray-300 rounded-md px-3 py-2 text-sm text-gray-800 placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent transition-shadow',
  formAddBtn:
    'bg-blue-600 hover:bg-blue-700 text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-gray-300 hover:text-red-500 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-white hover:bg-blue-50/40 transition-colors',
  formSectionBorder: 'border border-gray-100 rounded-lg',
  formSectionTitle: 'text-sm font-semibold text-gray-800',
  formItemChip: 'flex items-center gap-1 bg-gray-50 border border-gray-200 rounded px-2 py-1 text-xs text-gray-700 group',
  formItemText: 'text-xs text-gray-700 flex-1',
  canvasOuterBg: 'bg-gray-100',
  canvasWrapperBg: 'bg-white',
  canvasWrapperBorder: 'border border-gray-200',
  canvasWrapperShadow: 'shadow-xl',
  canvasTitle: 'text-gray-500 font-medium text-xs uppercase tracking-widest',
  blockBorder: '#e5e7eb',
  blockTitleBg: '#f3f4f6',
  blockTitleText: '#374151',
  blockTitleExtra: 'font-semibold text-[10px] uppercase tracking-widest',
  blockContentBg: '#ffffff',
  blockContentText: '#374151',
  blockItemColor: '#374151',
  blockBullet: '#9ca3af',
  blockShadow: 'none',
  blockRadius: '0px',
  blockBg: {
    keyPartnerships: '#f8fafc',
    keyActivities: '#fafafa',
    keyResources: '#fafafa',
    valuePropositions: '#eff6ff',
    customerRelationships: '#fdf4ff',
    channels: '#f0f9ff',
    customerSegments: '#fff7ed',
    costStructure: '#fef2f2',
    revenueStreams: '#f0fdf4',
  },
  btnPng: 'bg-emerald-600 hover:bg-emerald-700 text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  btnSave: 'bg-amber-500 hover:bg-amber-600 text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-gray-600 hover:bg-gray-700 text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  fontClass: 'font-sans',
  dividerColor: '#e5e7eb',
};

const neobrutalism: ThemeConfig = {
  id: 'neobrutalism',
  name: 'Neobrutalism',
  pageBg: 'bg-yellow-50',
  headerBg: 'bg-black',
  headerTitle: 'text-yellow-300 font-black text-lg uppercase tracking-widest',
  headerSubtitle: 'text-yellow-500 text-xs font-mono',
  sidebarBg: 'bg-yellow-50',
  sidebarBorder: 'border-r-4 border-black',
  formLabel: 'text-xs font-black text-black uppercase tracking-widest',
  formDescription: 'text-xs text-gray-600 mt-0.5 mb-2 font-mono',
  formInput:
    'w-full border-2 border-black px-3 py-2 text-sm font-mono text-black placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-yellow-400 bg-white',
  formAddBtn:
    'bg-black hover:bg-gray-800 text-yellow-300 text-xs font-black px-3 py-1.5 border-2 border-black transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-gray-400 hover:text-red-600 transition-colors ml-1 flex-shrink-0 font-black',
  formSectionBg: 'bg-yellow-50',
  formSectionBorder: 'border-2 border-black',
  formSectionTitle: 'text-xs font-black text-black uppercase',
  formItemChip: 'flex items-center gap-1 bg-white border-2 border-black px-2 py-1 text-xs text-black font-mono group',
  formItemText: 'text-xs text-black font-mono flex-1',
  canvasOuterBg: 'bg-yellow-50',
  canvasWrapperBg: 'bg-yellow-50',
  canvasWrapperBorder: 'border-4 border-black',
  canvasWrapperShadow: 'shadow-[8px_8px_0px_#000]',
  canvasTitle: 'text-black font-black text-xs uppercase tracking-widest font-mono',
  blockBorder: '#000000',
  blockTitleBg: '#000000',
  blockTitleText: '#fefce8',
  blockTitleExtra: 'font-black text-[10px] uppercase tracking-widest font-mono',
  blockContentBg: '#fffcf2',
  blockContentText: '#000000',
  blockItemColor: '#000000',
  blockBullet: '#000000',
  blockShadow: '3px 3px 0px #000',
  blockRadius: '0px',
  blockBg: {
    keyPartnerships: '#ffd6e0',
    keyActivities: '#fff3b0',
    keyResources: '#d4f5d4',
    valuePropositions: '#c8e6ff',
    customerRelationships: '#ead5ff',
    channels: '#ffd8a8',
    customerSegments: '#ffd6e0',
    costStructure: '#ffcccc',
    revenueStreams: '#ccf5cc',
  },
  btnPng: 'bg-green-400 hover:bg-green-300 text-black text-xs font-black px-3 py-1.5 border-2 border-black transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-blue-400 hover:bg-blue-300 text-black text-xs font-black px-3 py-1.5 border-2 border-black transition-colors flex items-center gap-1.5',
  btnSave: 'bg-yellow-400 hover:bg-yellow-300 text-black text-xs font-black px-3 py-1.5 border-2 border-black transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-gray-200 hover:bg-gray-100 text-black text-xs font-black px-3 py-1.5 border-2 border-black transition-colors flex items-center gap-1.5',
  fontClass: 'font-mono',
  dividerColor: '#000000',
};

const corporate: ThemeConfig = {
  id: 'corporate',
  name: 'Corporate',
  pageBg: 'bg-slate-100',
  headerBg: 'bg-slate-900',
  headerTitle: 'text-white font-bold text-lg tracking-tight',
  headerSubtitle: 'text-slate-400 text-xs',
  sidebarBg: 'bg-white',
  sidebarBorder: 'border-r border-slate-200',
  formLabel: 'text-sm font-semibold text-slate-700',
  formDescription: 'text-xs text-slate-400 mt-0.5 mb-2',
  formInput:
    'w-full border border-slate-300 px-3 py-2 text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-blue-700 focus:border-transparent transition-shadow rounded-sm',
  formAddBtn:
    'bg-blue-700 hover:bg-blue-800 text-white text-xs font-semibold px-3 py-1.5 rounded-sm transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-slate-300 hover:text-red-500 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-white hover:bg-blue-50/40 transition-colors',
  formSectionBorder: 'border border-slate-200 rounded-sm',
  formSectionTitle: 'text-sm font-semibold text-slate-800',
  formItemChip: 'flex items-center gap-1 bg-slate-50 border border-slate-200 px-2 py-1 text-xs text-slate-700 group rounded-sm',
  formItemText: 'text-xs text-slate-700 flex-1',
  canvasOuterBg: 'bg-slate-200',
  canvasWrapperBg: 'bg-white',
  canvasWrapperBorder: 'border border-slate-300',
  canvasWrapperShadow: 'shadow-2xl',
  canvasTitle: 'text-slate-500 font-semibold text-xs uppercase tracking-widest',
  blockBorder: '#cbd5e1',
  blockTitleBg: '#1e3a5f',
  blockTitleText: '#ffffff',
  blockTitleExtra: 'font-bold text-[10px] uppercase tracking-widest',
  blockContentBg: '#ffffff',
  blockContentText: '#334155',
  blockItemColor: '#334155',
  blockBullet: '#3b82f6',
  blockShadow: '0 1px 4px rgba(0,0,0,0.10)',
  blockRadius: '2px',
  blockBg: {
    keyPartnerships: '#dbeafe',
    keyActivities: '#dcfce7',
    keyResources: '#f3e8ff',
    valuePropositions: '#dbeafe',
    customerRelationships: '#fce7f3',
    channels: '#fef3c7',
    customerSegments: '#e0f7fa',
    costStructure: '#fce4ec',
    revenueStreams: '#dcfce7',
  },
  btnPng: 'bg-teal-700 hover:bg-teal-800 text-white text-xs font-semibold px-3 py-1.5 rounded-sm transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-blue-700 hover:bg-blue-800 text-white text-xs font-semibold px-3 py-1.5 rounded-sm transition-colors flex items-center gap-1.5',
  btnSave: 'bg-amber-700 hover:bg-amber-800 text-white text-xs font-semibold px-3 py-1.5 rounded-sm transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-slate-600 hover:bg-slate-700 text-white text-xs font-semibold px-3 py-1.5 rounded-sm transition-colors flex items-center gap-1.5',
  fontClass: 'font-serif',
  dividerColor: '#cbd5e1',
};

const hijau: ThemeConfig = {
  id: 'hijau',
  name: 'WBI',
  pageBg: 'bg-[#f0f5f2]',
  headerBg: 'bg-[#133622]',
  headerTitle: 'text-white font-bold text-lg tracking-tight',
  headerSubtitle: 'text-[#7fba9a] text-xs',
  sidebarBg: 'bg-white',
  sidebarBorder: 'border-r-2 border-[#50918B]',
  formLabel: 'text-sm font-semibold text-[#133622]',
  formDescription: 'text-xs text-[#50918B] mt-0.5 mb-2',
  formInput:
    'w-full border border-[#50918B] rounded px-3 py-2 text-sm text-[#133622] placeholder-[#a0b8b5] focus:outline-none focus:ring-2 focus:ring-[#AC7B2E] focus:border-transparent transition-shadow bg-white',
  formAddBtn:
    'bg-[#133622] hover:bg-[#1a4a2e] text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-[#a0b8b5] hover:text-red-500 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-white hover:bg-[#f0faf5] transition-colors',
  formSectionBorder: 'border border-[#c5ddd9] rounded',
  formSectionTitle: 'text-sm font-semibold text-[#133622]',
  formItemChip: 'flex items-center gap-1 bg-[#f0faf5] border border-[#c5ddd9] rounded px-2 py-1 text-xs text-[#133622] group',
  formItemText: 'text-xs text-[#133622] flex-1',
  canvasOuterBg: 'bg-[#e8f0ec]',
  canvasWrapperBg: 'bg-white',
  canvasWrapperBorder: 'border-2 border-[#50918B]',
  canvasWrapperShadow: 'shadow-2xl',
  canvasTitle: 'text-[#50918B] font-semibold text-xs uppercase tracking-widest',
  blockBorder: '#50918B',
  blockTitleBg: '#133622',
  blockTitleText: '#ffffff',
  blockTitleExtra: 'font-bold text-[10px] uppercase tracking-widest',
  blockContentBg: '#ffffff',
  blockContentText: '#1a3322',
  blockItemColor: '#1a3322',
  blockBullet: '#50918B',
  blockShadow: 'none',
  blockRadius: '0px',
  blockBg: {
    keyPartnerships: '#e8f4f2',
    keyActivities: '#eef7ee',
    keyResources: '#f5f0e8',
    valuePropositions: '#e8f4f0',
    customerRelationships: '#f5eee8',
    channels: '#eef0f5',
    customerSegments: '#f0e8f0',
    costStructure: '#fdf0e8',
    revenueStreams: '#e8f5ee',
  },
  btnPng: 'bg-[#50918B] hover:bg-[#3d7a74] text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-[#133622] hover:bg-[#1a4a2e] text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnSave: 'bg-[#AC7B2E] hover:bg-[#96691f] text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-white hover:bg-[#f0faf5] text-[#133622] border border-[#50918B] text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  fontClass: 'font-sans',
  dividerColor: '#50918B',
};

const blueprint: ThemeConfig = {
  id: 'blueprint',
  name: 'Blueprint',
  pageBg: 'bg-sky-950',
  headerBg: 'bg-sky-900 border-b border-sky-700',
  headerTitle: 'text-sky-100 font-bold text-lg tracking-[0.12em] uppercase',
  headerSubtitle: 'text-sky-300 text-xs font-mono',
  sidebarBg: 'bg-sky-950',
  sidebarBorder: 'border-r border-sky-700',
  formLabel: 'text-xs font-bold text-sky-100 uppercase tracking-widest',
  formDescription: 'text-xs text-sky-300 mt-0.5 mb-2 font-mono',
  formInput:
    'w-full border border-sky-600 rounded px-3 py-2 text-sm text-sky-50 placeholder-sky-400 focus:outline-none focus:ring-2 focus:ring-cyan-300 bg-sky-900/70',
  formAddBtn:
    'bg-cyan-300 hover:bg-cyan-200 text-sky-950 text-xs font-bold px-3 py-1.5 rounded transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-sky-400 hover:text-red-300 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-sky-900/60 hover:bg-sky-900/80 transition-colors',
  formSectionBorder: 'border border-sky-700 rounded',
  formSectionTitle: 'text-sm font-semibold text-sky-50',
  formItemChip: 'flex items-center gap-1 bg-sky-950/80 border border-sky-700 rounded px-2 py-1 text-xs text-sky-100 group',
  formItemText: 'text-xs text-sky-100 flex-1',
  canvasOuterBg: 'bg-sky-950',
  canvasWrapperBg: 'bg-sky-950',
  canvasWrapperBorder: 'border-2 border-sky-500',
  canvasWrapperShadow: 'shadow-[0_0_0_1px_rgba(125,211,252,0.25),0_24px_60px_rgba(2,6,23,0.45)]',
  canvasTitle: 'text-sky-200 font-semibold text-xs uppercase tracking-widest',
  blockBorder: '#38bdf8',
  blockTitleBg: '#082f49',
  blockTitleText: '#e0f2fe',
  blockTitleExtra: 'font-bold text-[10px] uppercase tracking-widest font-mono',
  blockContentBg: '#0c4a6e',
  blockContentText: '#e0f2fe',
  blockItemColor: '#e0f2fe',
  blockBullet: '#67e8f9',
  blockShadow: 'inset 0 0 0 1px rgba(125,211,252,0.18)',
  blockRadius: '4px',
  blockBg: {
    keyPartnerships: '#0b3954',
    keyActivities: '#0c4a6e',
    keyResources: '#075985',
    valuePropositions: '#164e63',
    customerRelationships: '#1e3a8a',
    channels: '#155e75',
    customerSegments: '#082f49',
    costStructure: '#172554',
    revenueStreams: '#083344',
  },
  btnPng: 'bg-cyan-300 hover:bg-cyan-200 text-sky-950 text-xs font-bold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-sky-500 hover:bg-sky-400 text-white text-xs font-bold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnSave: 'bg-blue-500 hover:bg-blue-400 text-white text-xs font-bold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-sky-900 hover:bg-sky-800 text-sky-100 border border-sky-600 text-xs font-bold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  fontClass: 'font-mono',
  dividerColor: '#38bdf8',
};

const paper: ThemeConfig = {
  id: 'paper',
  name: 'Paper',
  pageBg: 'bg-stone-100',
  headerBg: 'bg-[#f7f1e3] border-b border-[#d9c8ad]',
  headerTitle: 'text-[#5b4631] font-bold text-lg tracking-tight',
  headerSubtitle: 'text-[#8b7355] text-xs',
  sidebarBg: 'bg-[#fffaf0]',
  sidebarBorder: 'border-r border-[#e6d7bf]',
  formLabel: 'text-sm font-semibold text-[#5b4631]',
  formDescription: 'text-xs text-[#8b7355] mt-0.5 mb-2',
  formInput:
    'w-full border border-[#d7c5a9] rounded px-3 py-2 text-sm text-[#4b3b2a] placeholder-[#b19b7a] focus:outline-none focus:ring-2 focus:ring-[#b08968] bg-[#fffdf8]',
  formAddBtn:
    'bg-[#8b6b4a] hover:bg-[#72563b] text-[#fffaf0] text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-[#b19b7a] hover:text-red-500 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-[#fffaf0] hover:bg-[#fff5e6] transition-colors',
  formSectionBorder: 'border border-[#eadcc7] rounded-lg',
  formSectionTitle: 'text-sm font-semibold text-[#5b4631]',
  formItemChip: 'flex items-center gap-1 bg-[#fffdf8] border border-[#eadcc7] rounded px-2 py-1 text-xs text-[#5b4631] group',
  formItemText: 'text-xs text-[#5b4631] flex-1',
  canvasOuterBg: 'bg-[#efe6d6]',
  canvasWrapperBg: 'bg-[#fffaf0]',
  canvasWrapperBorder: 'border border-[#d9c8ad]',
  canvasWrapperShadow: 'shadow-xl',
  canvasTitle: 'text-[#8b7355] font-medium text-xs uppercase tracking-widest',
  blockBorder: '#d7c5a9',
  blockTitleBg: '#ede0c8',
  blockTitleText: '#5b4631',
  blockTitleExtra: 'font-semibold text-[10px] uppercase tracking-widest',
  blockContentBg: '#fffaf0',
  blockContentText: '#5b4631',
  blockItemColor: '#5b4631',
  blockBullet: '#b08968',
  blockShadow: '0 1px 4px rgba(120,96,72,0.08)',
  blockRadius: '6px',
  blockBg: {
    keyPartnerships: '#f8efe0',
    keyActivities: '#fff5e6',
    keyResources: '#fdf1e3',
    valuePropositions: '#fff7e6',
    customerRelationships: '#faf0e6',
    channels: '#fff3dd',
    customerSegments: '#fdf0d5',
    costStructure: '#f9ece2',
    revenueStreams: '#eef6e8',
  },
  btnPng: 'bg-[#6b8f71] hover:bg-[#5a7a60] text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-[#8b6b4a] hover:bg-[#72563b] text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnSave: 'bg-[#c08552] hover:bg-[#a86f41] text-white text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-[#fffdf8] hover:bg-[#f7efe2] text-[#5b4631] border border-[#d7c5a9] text-xs font-semibold px-3 py-1.5 rounded transition-colors flex items-center gap-1.5',
  fontClass: 'font-serif',
  dividerColor: '#d7c5a9',
};

const playfulEducation: ThemeConfig = {
  id: 'playfulEducation',
  name: 'Playful Education',
  pageBg: 'bg-[#f5f7ff]',
  headerBg: 'bg-gradient-to-r from-violet-500 via-sky-500 to-cyan-400',
  headerTitle: 'text-white font-black text-lg tracking-tight',
  headerSubtitle: 'text-cyan-50 text-xs',
  sidebarBg: 'bg-white',
  sidebarBorder: 'border-r border-violet-100',
  formLabel: 'text-sm font-bold text-violet-700',
  formDescription: 'text-xs text-sky-500 mt-0.5 mb-2',
  formInput:
    'w-full border border-violet-200 rounded-xl px-3 py-2 text-sm text-slate-700 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-violet-400 bg-white',
  formAddBtn:
    'bg-violet-500 hover:bg-violet-600 text-white text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-violet-300 hover:text-rose-500 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-white hover:bg-violet-50 transition-colors',
  formSectionBorder: 'border border-violet-100 rounded-2xl',
  formSectionTitle: 'text-sm font-bold text-slate-700',
  formItemChip: 'flex items-center gap-1 bg-violet-50 border border-violet-100 rounded-xl px-2 py-1 text-xs text-slate-700 group',
  formItemText: 'text-xs text-slate-700 flex-1',
  canvasOuterBg: 'bg-[#eef2ff]',
  canvasWrapperBg: 'bg-white',
  canvasWrapperBorder: 'border border-violet-100',
  canvasWrapperShadow: 'shadow-[0_20px_40px_rgba(124,58,237,0.12)]',
  canvasTitle: 'text-violet-400 font-semibold text-xs uppercase tracking-widest',
  blockBorder: '#ddd6fe',
  blockTitleBg: '#8b5cf6',
  blockTitleText: '#ffffff',
  blockTitleExtra: 'font-bold text-[10px] uppercase tracking-widest',
  blockContentBg: '#ffffff',
  blockContentText: '#334155',
  blockItemColor: '#334155',
  blockBullet: '#22c55e',
  blockShadow: '0 6px 16px rgba(139,92,246,0.08)',
  blockRadius: '14px',
  blockBg: {
    keyPartnerships: '#fef3c7',
    keyActivities: '#dcfce7',
    keyResources: '#ffe4e6',
    valuePropositions: '#dbeafe',
    customerRelationships: '#fce7f3',
    channels: '#cffafe',
    customerSegments: '#ede9fe',
    costStructure: '#fee2e2',
    revenueStreams: '#dcfce7',
  },
  btnPng: 'bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-violet-500 hover:bg-violet-600 text-white text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  btnSave: 'bg-amber-400 hover:bg-amber-500 text-slate-900 text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-sky-500 hover:bg-sky-600 text-white text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  fontClass: 'font-sans',
  dividerColor: '#ddd6fe',
};

const notion: ThemeConfig = {
  id: 'notion',
  name: 'Notion',
  pageBg: 'bg-[#f7f6f3]',
  headerBg: 'bg-[#ffffff] border-b border-[#e9e7e3]',
  headerTitle: 'text-[#191919] font-bold text-lg tracking-tight',
  headerSubtitle: 'text-[#787774] text-xs',
  sidebarBg: 'bg-[#fbfbfa]',
  sidebarBorder: 'border-r border-[#eceae5]',
  formLabel: 'text-sm font-semibold text-[#37352f]',
  formDescription: 'text-xs text-[#9b9995] mt-0.5 mb-2',
  formInput:
    'w-full border border-[#e6e4e0] rounded-md px-3 py-2 text-sm text-[#37352f] placeholder-[#b5b2ac] focus:outline-none focus:ring-2 focus:ring-[#2f80ed] bg-white',
  formAddBtn:
    'bg-[#191919] hover:bg-[#2f2f2f] text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-[#c8c5bf] hover:text-red-500 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-white hover:bg-[#f7f6f3] transition-colors',
  formSectionBorder: 'border border-[#eceae5] rounded-xl',
  formSectionTitle: 'text-sm font-semibold text-[#37352f]',
  formItemChip: 'flex items-center gap-1 bg-[#f7f6f3] border border-[#eceae5] rounded-md px-2 py-1 text-xs text-[#37352f] group',
  formItemText: 'text-xs text-[#37352f] flex-1',
  canvasOuterBg: 'bg-[#f1efeb]',
  canvasWrapperBg: 'bg-white',
  canvasWrapperBorder: 'border border-[#eceae5]',
  canvasWrapperShadow: 'shadow-xl',
  canvasTitle: 'text-[#9b9995] font-medium text-xs uppercase tracking-widest',
  blockBorder: '#eceae5',
  blockTitleBg: '#f7f6f3',
  blockTitleText: '#37352f',
  blockTitleExtra: 'font-semibold text-[10px] uppercase tracking-widest',
  blockContentBg: '#ffffff',
  blockContentText: '#37352f',
  blockItemColor: '#37352f',
  blockBullet: '#2f80ed',
  blockShadow: 'none',
  blockRadius: '10px',
  blockBg: {
    keyPartnerships: '#ffffff',
    keyActivities: '#fcfcfb',
    keyResources: '#fbfbfa',
    valuePropositions: '#ffffff',
    customerRelationships: '#fcfcfb',
    channels: '#fbfbfa',
    customerSegments: '#ffffff',
    costStructure: '#fcfcfb',
    revenueStreams: '#ffffff',
  },
  btnPng: 'bg-[#2f80ed] hover:bg-[#256bcb] text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-[#191919] hover:bg-[#2f2f2f] text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  btnSave: 'bg-[#d97706] hover:bg-[#b45309] text-white text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-[#f7f6f3] hover:bg-[#eceae5] text-[#37352f] border border-[#e6e4e0] text-xs font-semibold px-3 py-1.5 rounded-md transition-colors flex items-center gap-1.5',
  fontClass: 'font-sans',
  dividerColor: '#eceae5',
};

const glassmorphism: ThemeConfig = {
  id: 'glassmorphism',
  name: 'Glassmorphism',
  pageBg: 'bg-gradient-to-br from-slate-900 via-indigo-950 to-sky-950',
  headerBg: 'bg-white/10 backdrop-blur-xl border-b border-white/15',
  headerTitle: 'text-white font-bold text-lg tracking-tight',
  headerSubtitle: 'text-sky-100/70 text-xs',
  sidebarBg: 'bg-white/10 backdrop-blur-xl',
  sidebarBorder: 'border-r border-white/10',
  formLabel: 'text-sm font-semibold text-white',
  formDescription: 'text-xs text-sky-100/70 mt-0.5 mb-2',
  formInput:
    'w-full border border-white/15 rounded-xl px-3 py-2 text-sm text-white placeholder-white/45 focus:outline-none focus:ring-2 focus:ring-cyan-300 bg-white/10 backdrop-blur-md',
  formAddBtn:
    'bg-cyan-400/90 hover:bg-cyan-300 text-slate-950 text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-white/40 hover:text-red-300 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-white/8 backdrop-blur-lg hover:bg-white/12 transition-colors',
  formSectionBorder: 'border border-white/12 rounded-2xl',
  formSectionTitle: 'text-sm font-semibold text-white',
  formItemChip: 'flex items-center gap-1 bg-white/10 border border-white/10 rounded-xl px-2 py-1 text-xs text-white group',
  formItemText: 'text-xs text-white flex-1',
  canvasOuterBg: 'bg-transparent',
  canvasWrapperBg: 'bg-white/10',
  canvasWrapperBorder: 'border border-white/15',
  canvasWrapperShadow: 'shadow-[0_18px_60px_rgba(15,23,42,0.45)]',
  canvasTitle: 'text-sky-100/70 font-medium text-xs uppercase tracking-widest',
  blockBorder: 'rgba(255,255,255,0.18)',
  blockTitleBg: 'rgba(255,255,255,0.14)',
  blockTitleText: '#f8fafc',
  blockTitleExtra: 'font-semibold text-[10px] uppercase tracking-widest',
  blockContentBg: 'rgba(255,255,255,0.08)',
  blockContentText: '#f8fafc',
  blockItemColor: '#f8fafc',
  blockBullet: '#67e8f9',
  blockShadow: '0 10px 30px rgba(15,23,42,0.18)',
  blockRadius: '18px',
  blockBg: {
    keyPartnerships: 'rgba(59,130,246,0.16)',
    keyActivities: 'rgba(16,185,129,0.16)',
    keyResources: 'rgba(168,85,247,0.16)',
    valuePropositions: 'rgba(34,211,238,0.16)',
    customerRelationships: 'rgba(236,72,153,0.16)',
    channels: 'rgba(249,115,22,0.16)',
    customerSegments: 'rgba(99,102,241,0.18)',
    costStructure: 'rgba(244,63,94,0.16)',
    revenueStreams: 'rgba(16,185,129,0.18)',
  },
  btnPng: 'bg-emerald-400/90 hover:bg-emerald-300 text-slate-950 text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-cyan-400/90 hover:bg-cyan-300 text-slate-950 text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  btnSave: 'bg-amber-300/90 hover:bg-amber-200 text-slate-950 text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-white/10 hover:bg-white/15 text-white border border-white/15 text-xs font-bold px-3 py-1.5 rounded-xl transition-colors flex items-center gap-1.5',
  fontClass: 'font-sans',
  dividerColor: 'rgba(255,255,255,0.12)',
};

const startupPitchDeck: ThemeConfig = {
  id: 'startupPitchDeck',
  name: 'Startup Pitch Deck',
  pageBg: 'bg-[#0f172a]',
  headerBg: 'bg-[#111827]',
  headerTitle: 'text-white font-black text-lg tracking-tight',
  headerSubtitle: 'text-fuchsia-300 text-xs uppercase tracking-widest',
  sidebarBg: 'bg-white',
  sidebarBorder: 'border-r border-slate-200',
  formLabel: 'text-sm font-semibold text-slate-800',
  formDescription: 'text-xs text-slate-500 mt-0.5 mb-2',
  formInput:
    'w-full border border-slate-300 rounded-lg px-3 py-2 text-sm text-slate-800 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-fuchsia-500 bg-white',
  formAddBtn:
    'bg-fuchsia-600 hover:bg-fuchsia-700 text-white text-xs font-bold px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1',
  formRemoveBtn: 'text-slate-300 hover:text-rose-500 transition-colors ml-1 flex-shrink-0',
  formSectionBg: 'bg-white hover:bg-fuchsia-50 transition-colors',
  formSectionBorder: 'border border-slate-100 rounded-xl',
  formSectionTitle: 'text-sm font-semibold text-slate-800',
  formItemChip: 'flex items-center gap-1 bg-slate-50 border border-slate-200 rounded-lg px-2 py-1 text-xs text-slate-700 group',
  formItemText: 'text-xs text-slate-700 flex-1',
  canvasOuterBg: 'bg-[#111827]',
  canvasWrapperBg: 'bg-white',
  canvasWrapperBorder: 'border border-slate-200',
  canvasWrapperShadow: 'shadow-[0_24px_60px_rgba(15,23,42,0.35)]',
  canvasTitle: 'text-slate-400 font-semibold text-xs uppercase tracking-widest',
  blockBorder: '#e2e8f0',
  blockTitleBg: '#111827',
  blockTitleText: '#ffffff',
  blockTitleExtra: 'font-bold text-[10px] uppercase tracking-widest',
  blockContentBg: '#ffffff',
  blockContentText: '#334155',
  blockItemColor: '#334155',
  blockBullet: '#d946ef',
  blockShadow: '0 10px 24px rgba(15,23,42,0.08)',
  blockRadius: '12px',
  blockBg: {
    keyPartnerships: '#eef2ff',
    keyActivities: '#ecfeff',
    keyResources: '#f5f3ff',
    valuePropositions: '#fdf2f8',
    customerRelationships: '#fae8ff',
    channels: '#eff6ff',
    customerSegments: '#fff7ed',
    costStructure: '#fff1f2',
    revenueStreams: '#ecfdf5',
  },
  btnPng: 'bg-emerald-500 hover:bg-emerald-600 text-white text-xs font-bold px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1.5',
  btnPdf: 'bg-fuchsia-600 hover:bg-fuchsia-700 text-white text-xs font-bold px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1.5',
  btnSave: 'bg-slate-900 hover:bg-black text-white text-xs font-bold px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1.5',
  btnLoad: 'bg-white hover:bg-slate-50 text-slate-800 border border-slate-200 text-xs font-bold px-3 py-1.5 rounded-lg transition-colors flex items-center gap-1.5',
  fontClass: 'font-sans',
  dividerColor: '#e2e8f0',
};

export const themes: Record<ThemeId, ThemeConfig> = {
  hijau,
  minimalist,
  neobrutalism,
  corporate,
  blueprint,
  paper,
  playfulEducation,
  notion,
  glassmorphism,
  startupPitchDeck,
};

export const themeOrder: ThemeId[] = [
  'hijau',
  'minimalist',
  'neobrutalism',
  'corporate',
  'blueprint',
  'paper',
  'playfulEducation',
  'notion',
  'glassmorphism',
  'startupPitchDeck',
];
